name: "Ecommerce-app"
on:
  push:
    branches:
      - main
      - app-test
    paths:
      - ecommerce-app/**
  pull_request:
    branches:
      - main
    paths:
      - ecommerce-app/**

env:
  AWS_REGION: "us-east-1"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
  TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_db_username: ${{ secrets.RDS_USER_NAME }}
  TF_VAR_db_password: ${{ secrets.RDS_PASSWORD }}

jobs:
    Build_and_Test:
        name: "Build and Testing Ecommerce App"
        runs-on: ubuntu-latest
        defaults:
          run:
            shell: bash
            working-directory: ecommerce-app/

        steps:
              - name: Checkout code
                uses: actions/checkout@v2

              - name: Set up Python
                uses: actions/setup-python@v2
                with:
                  python-version: '3.10'

              - name: Install dependencies
                run: pip install -r requirements.txt pytest

              - name: Run tests
                run: pytest --junitxml=reports/test-results.xml

              - name: Package the application
                run: zip -r ecommerce-app.zip . -x "*.git*" "tests/*" "*.pytest_cache*" "*.DS_Store"

              - name: Upload artifact
                uses: einaregilsson/beanstalk-deploy@v20
                with:
                    aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    application_name: "ecommerce-app"
                    environment_name: "ecommerce-env"
                    version_label: ${{ github.sha }}
                    region: "us-east-1"
                    deployment_package: "ecommerce-app.zip"